### ISSUE TITLE
User Agent parser missing quot cases

### ISSUE THREAD

**Issue by ghost** [armatusmiles/sipcore#34]
https://github.com/kurotych/sipcore/blob/0ca37a4834e58c4eefeeb6f29fd1271746f99f45/crates/sipmsg/src/headers/parsers/user_agent.rs#L22

In some SIP samples from Wireshark project contained the following UA :

`User-Agent: <Motorola VT1000 mac: 000CE5C74EF8 sw:VT20_02.03.00_A ln:0 cfg:1253778536520/1002173358>`

This fails because quot cases not handled, maybe :

```
            if tmp_input[0] == b'<' {
                let (input, _) = take_sws_token::laquot(tmp_input)?;
                let (input, _) = take_until(">")(input)?;
                let (input, _) = take_sws_token::raquot(input)?;
                tmp_input = input;
                continue;
            }
```

**Comment by kurotych** [comment]
Hello @q6,

Thank you for contribution. User agent values are really crazy thing.
I've added your fix to master and released Sipmsg 0.2.3 version.

Best regards,

Anatolii
